target-version = "py314"

lint.select = ["ALL"]

lint.ignore = [
    "ANN001",   # Missing type annotation for function argument
    "ANN201",   # Missing return type annotation for public function
    "C901",     # too complex
    "COM812",   # Trailing comma missing
    "D203",     # 1 blank line required before class docstring
    "D213",     # Multi-line docstring summary should start at the second line
    "D404",     # First word of the docstring should not be This
    "E501",     # Line too long
    "EM101",    # Exception must not use a string literal, assign to variable first
    "EM102",    # Exception must not use an f-string literal, assign to variable first
    "FBT002",   # Boolean default value in function definition
    "FBT003",   # Boolean positional value in function call
    "INP001",   # Add an `__init__.py`
    "TRY003",   # Avoid specifying long messages outside the exception class
]

[lint.mccabe]
max-complexity = 25
